# Enable cache
#spring.web.resources.cache.cachecontrol.max-age=30d
# Enable gzip html css js
server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain,text/css,application/javascript
server.compression.min-response-size=1024
## Enable cache of static
# Tat di vi cache nay anh huong toi css
#spring.web.resources.cache.period=365d
#spring.web.resources.chain.cache=true
# SQL server:
# Payment gateway test only
#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=EventGo_TestPayment;encrypt=false;
#spring.datasource.url=jdbc:sqlserver://103.200.21.220;databaseName=EventGo_TestPayment;encrypt=false;
#spring.datasource.url=jdbc:sqlserver://103.200.21.220;databaseName=EventGo_Test;encrypt=false;
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EventManagementSystem;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# Naming
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=285409961213-hsu41rad22scimqqdrto129vvmg3uo75.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# Revenue API
revenue.api.key=

# Query hibernate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# DEV mode not authorize
#spring.profiles.active=dev

# PROD
# Deploy to server
spring.profiles.active=prod
# Session timeout
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.max-age=-1
server.servlet.session.timeout=2592000
#UPLOAD FILE
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Do not restart connection:
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=20MB

# =============================================
#  MAIL CONFIG - Gmail SMTP
# =============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8
# =============================================
# OTP CONFIG
# =============================================
otp.expiry-minutes=2
#src/main/resources/application.properties
# =============================================
# AVATAR UPLOAD ? profile feature
# =============================================
app.upload.avatar-dir=upload/avatars
app.upload.avatar-url-prefix=/upload/avatars

# Log request
spring.mvc.log-request-details=true


# DEV mode Khi deploy phai tat di
#spring.web.resources.chain.cache=false
#spring.web.resources.cache.period=0
#spring.thymeleaf.cache=false

#VietMap
api.vietmap.key=8395f84a09ddc7f7b9c9f85126d4a5e27b7f4fbe0eb0714c


# VNPAY
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmn-code=9QOBIFQI
vnpay.secret-key=6G6MR78UBG5Q77ZPVJLJC77FUMR5EDUY
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

spring.thymeleaf.encoding=UTF-8

#logging.level.org.springframework.security=DEBUG
spring.servlet.multipart.resolve-lazily=true

# DEV
spring.datasource.url=jdbc:sqlserver://103.200.21.220;databaseName=HSF302_Group4_Demo;encrypt=false;
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
upload.root=${user.dir}
vnpay.return-url=http://localhost:8080/payment-return

# DEPLOY TO SERVER
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF302_Group4_Demo;encrypt=false;
#upload.root=/opt
#vnpay.return-url=https://www.eventgo.pro.vn/payment-return
#spring.security.oauth2.client.registration.google.redirect-uri=https://www.eventgo.pro.vn/login/oauth2/code/google
